ALTER TABLE posts CHANGE COLUMN curso tema VARCHAR(50) NOT NULL;

UPDATE posts
SET tema = CASE tema
    WHEN 'JAVA' THEN 'TECNOLOGIA'
    WHEN 'SPRING_BOOT' THEN 'COTIDIANO'
    WHEN 'MYSQL' THEN 'LIVROS'
    WHEN 'SEGURANCA' THEN 'SOCIEDADE'
    WHEN 'API_REST' THEN 'IDEIAS'
    WHEN 'DEVOPS' THEN 'TRABALHO'
    WHEN 'FRONTEND' THEN 'CULTURA'
    ELSE tema
END;
